# Generated by Django 3.0.5 on 2020-04-16 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0002_initial_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(blank=True, max_length=1024, null=True)),
                ('lastName', models.CharField(blank=True, max_length=1024, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.CharField(blank=True, max_length=512, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='publication',
            name='date',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='publications.Person')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='publications.Role')),
            ],
        ),
        migrations.AddField(
            model_name='publication',
            name='creators',
            field=models.ManyToManyField(to='publications.Creator'),
        ),
    ]
