# Generated by Django 3.0.5 on 2020-04-16 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0008_auto_20200416_0904'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='key',
            new_name='zoterokey',
        ),
    ]
