# Generated by Django 3.0.5 on 2020-04-16 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0009_auto_20200416_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='year',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
