# Generated by Django 3.0.5 on 2020-04-16 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0010_auto_20200416_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='artworkMedium',
            field=models.CharField(default='', max_length=2024),
        ),
        migrations.AddField(
            model_name='publication',
            name='artworkSize',
            field=models.CharField(default='', max_length=1024),
        ),
    ]
