# Generated by Django 3.0.5 on 2020-04-16 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0012_collection_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='volume',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
