# Generated by Django 3.0.5 on 2020-04-16 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0015_imageattachment_pdfattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='publications.Collection'),
        ),
        migrations.AlterField(
            model_name='creator',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publications.Person'),
        ),
        migrations.AlterField(
            model_name='creator',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publications.Role'),
        ),
    ]
