# Generated by Django 3.0.5 on 2020-04-23 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0016_auto_20200416_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageattachment',
            name='tags',
            field=models.ManyToManyField(blank=True, to='publications.Tag'),
        ),
        migrations.AddField(
            model_name='pdfattachment',
            name='tags',
            field=models.ManyToManyField(blank=True, to='publications.Tag'),
        ),
        migrations.AddField(
            model_name='publication',
            name='tags',
            field=models.ManyToManyField(blank=True, to='publications.Tag'),
        ),
        migrations.AlterField(
            model_name='imageattachment',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publications.Publication'),
        ),
        migrations.AlterField(
            model_name='pdfattachment',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publications.Publication'),
        ),
    ]
