# Generated by Django 3.0.5 on 2020-04-25 09:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.file
import filer.fields.image
import publications.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('filer', '0011_auto_20190418_0137'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2024)),
            ],
        ),
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name_plural': 'Lists',
                'ordering': ('list',),
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(blank=True, max_length=1024, null=True)),
                ('lastName', models.CharField(blank=True, max_length=1024, null=True)),
                ('name', models.CharField(blank=True, max_length=1024, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.CharField(blank=True, max_length=512, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2024)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False)),
                ('type', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=128)),
                ('zotero_types', models.CharField(default='', help_text='Possible Zotero types, separated by comma.', max_length=256, verbose_name='zotero type')),
                ('bibtex_types', models.CharField(default='article', help_text='Possible BibTex types, separated by comma.', max_length=256, verbose_name='BibTex types')),
                ('hidden', models.BooleanField(default=False, help_text='Hide publications from main view.')),
            ],
            options={
                'verbose_name_plural': '  Types',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zoterokey', models.CharField(blank=True, help_text='Zotero key. Leave blank if unsure.', max_length=512, null=True)),
                ('citekey', models.CharField(blank=True, help_text='BibTex citation key. Leave blank if unsure.', max_length=512, null=True)),
                ('title', models.CharField(max_length=512)),
                ('authors', models.CharField(help_text='List of authors separated by commas or <i>and</i>.', max_length=2048)),
                ('year', models.PositiveIntegerField(default=0)),
                ('month', models.IntegerField(blank=True, choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], null=True)),
                ('date', models.CharField(blank=True, max_length=256)),
                ('journal', models.CharField(blank=True, max_length=256)),
                ('book_title', models.CharField(blank=True, max_length=256)),
                ('publisher', models.CharField(blank=True, max_length=256)),
                ('institution', models.CharField(blank=True, max_length=256)),
                ('volume', models.CharField(blank=True, max_length=256, null=True)),
                ('number', models.IntegerField(blank=True, null=True, verbose_name='Issue number')),
                ('pages', publications.fields.PagesField(blank=True, max_length=32)),
                ('note', models.CharField(blank=True, max_length=256)),
                ('keywords', models.CharField(blank=True, help_text='List of keywords separated by commas.', max_length=256)),
                ('url', models.URLField(blank=True, help_text='Link to PDF or journal page.', verbose_name='URL')),
                ('code', models.URLField(blank=True, help_text='Link to page with code.')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='publications/', verbose_name='PDF')),
                ('image', models.ImageField(blank=True, null=True, upload_to='publications/images/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='publications/thumbnails/')),
                ('doi', models.CharField(blank=True, max_length=128, verbose_name='DOI')),
                ('external', models.BooleanField(default=False, help_text='If publication was written in another lab, mark as external.')),
                ('abstract', models.TextField(blank=True)),
                ('isbn', models.CharField(blank=True, help_text='Only for a book.', max_length=32, verbose_name='ISBN')),
                ('artworkMedium', models.CharField(default='', max_length=2024)),
                ('artworkSize', models.CharField(default='', max_length=1024)),
                ('creators', models.ManyToManyField(to='publications.Creator')),
                ('lists', models.ManyToManyField(blank=True, to='publications.List')),
                ('tags', models.ManyToManyField(blank=True, to='publications.Tag')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publications.Type')),
            ],
            options={
                'verbose_name_plural': ' Publications',
                'ordering': ['-year', '-month', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PDFAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zoterokey', models.CharField(max_length=30)),
                ('file', filer.fields.file.FilerFileField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='filer.File')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publications.Publication')),
                ('tags', models.ManyToManyField(blank=True, to='publications.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='ImageAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zoterokey', models.CharField(max_length=30)),
                ('file', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.FILER_IMAGE_MODEL)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publications.Publication')),
                ('tags', models.ManyToManyField(blank=True, to='publications.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='CustomLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=256)),
                ('url', models.URLField(verbose_name='URL')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publications.Publication')),
            ],
        ),
        migrations.CreateModel(
            name='CustomFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=256)),
                ('file', models.FileField(upload_to='publications/')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publications.Publication')),
            ],
        ),
        migrations.AddField(
            model_name='creator',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publications.Person'),
        ),
        migrations.AddField(
            model_name='creator',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publications.Role'),
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zoterokey', models.CharField(max_length=100)),
                ('name', models.CharField(default='', max_length=2024)),
                ('items', models.ManyToManyField(to='publications.Publication')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='publications.Collection')),
            ],
        ),
    ]
