# Generated by Django 3.0.5 on 2020-04-27 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0002_initial_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10000)),
            ],
        ),
        migrations.AddField(
            model_name='publication',
            name='archive',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='publications.Archive'),
        ),
        migrations.AddField(
            model_name='publication',
            name='callNumber',
            field=models.CharField(default='', max_length=3000),
        ),
        migrations.AddField(
            model_name='publication',
            name='rights',
            field=models.CharField(default='', max_length=3000),
        ),
        migrations.AlterField(
            model_name='publication',
            name='authors',
            field=models.CharField(help_text='List of authors separated by commas or <i>and</i>.', max_length=10000),
        ),
        migrations.AlterField(
            model_name='publication',
            name='book_title',
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='publication',
            name='code',
            field=models.URLField(blank=True, help_text='Link to page with code.', max_length=5000),
        ),
        migrations.AlterField(
            model_name='publication',
            name='note',
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='publication',
            name='title',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='publication',
            name='url',
            field=models.URLField(blank=True, help_text='Link to PDF or journal page.', max_length=5000, verbose_name='URL'),
        ),
        migrations.AddField(
            model_name='archive',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='publications.Place'),
        ),
        migrations.AddField(
            model_name='publication',
            name='place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='publications.Place'),
        ),
    ]
