# Generated by Django 3.0.5 on 2020-06-03 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0003_auto_20200427_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageattachment',
            name='zoterokey',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='pdfattachment',
            name='zoterokey',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.CreateModel(
            name='URLAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zoterokey', models.CharField(blank=True, max_length=30, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publications.Publication')),
                ('tags', models.ManyToManyField(blank=True, to='publications.Tag')),
            ],
        ),
    ]
