# Generated by Django 3.0.5 on 2020-06-04 15:29

from django.db import migrations
import django.db.models.deletion
import filer.fields.file


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0011_auto_20190418_0137'),
        ('publications', '0005_auto_20200604_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=filer.fields.file.FilerFileField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='filer.File'),
        ),
    ]
