# Generated by Django 3.0.5 on 2020-06-05 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0009_auto_20200605_0831'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='has_abstract_modified',
            field=models.BooleanField(default=False),
        ),
    ]
