# Generated by Django 3.0.5 on 2020-06-05 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0010_publication_has_abstract_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='counts',
            field=models.CharField(blank=True, default={}, max_length=10000, null=True),
        ),
    ]
