# Generated by Django 3.0.5 on 2020-06-09 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0011_collection_counts'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='derived_from',
            field=models.ManyToManyField(blank=True, null=True, to='publications.Attachment'),
        ),
        migrations.AddField(
            model_name='imageattachment',
            name='derived_from',
            field=models.ManyToManyField(blank=True, null=True, to='publications.Attachment'),
        ),
        migrations.AddField(
            model_name='pdfattachment',
            name='derived_from',
            field=models.ManyToManyField(blank=True, null=True, to='publications.Attachment'),
        ),
        migrations.AddField(
            model_name='urlattachment',
            name='derived_from',
            field=models.ManyToManyField(blank=True, null=True, to='publications.Attachment'),
        ),
    ]
