# Generated by Django 3.0.5 on 2020-06-10 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0012_auto_20200609_0805'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='solr_id',
            field=models.CharField(blank=True, help_text='solr_id. Leave blank if unsure.', max_length=1000, null=True),
        ),
    ]
