# Generated by Django 3.0.5 on 2020-06-10 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0013_publication_solr_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='NER_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='NER_object',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5000)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publications.NER_type')),
            ],
        ),
        migrations.AddField(
            model_name='publication',
            name='ner_objects',
            field=models.ManyToManyField(blank=True, to='publications.NER_object'),
        ),
    ]
