# Generated by Django 3.0.5 on 2020-06-10 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0014_auto_20200610_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='has_external_files',
            field=models.BooleanField(default=False),
        ),
    ]
