# Generated by Django 3.0.5 on 2020-06-10 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0015_publication_has_external_files'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publication',
            old_name='has_external_files',
            new_name='has_urls',
        ),
    ]
