# Generated by Django 3.0.5 on 2020-06-16 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0017_auto_20200615_1208'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormatType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2024)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessingType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2024)),
            ],
        ),
        migrations.RenameField(
            model_name='attachment',
            old_name='type',
            new_name='type_of_text',
        ),
        migrations.RenameField(
            model_name='collectionattachment',
            old_name='type',
            new_name='type_of_text',
        ),
        migrations.RenameField(
            model_name='imageattachment',
            old_name='type',
            new_name='type_of_text',
        ),
        migrations.RenameField(
            model_name='pdfattachment',
            old_name='type',
            new_name='type_of_text',
        ),
        migrations.RenameField(
            model_name='urlattachment',
            old_name='type',
            new_name='type_of_text',
        ),
        migrations.AddField(
            model_name='collectionattachment',
            name='format',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='publications.FormatType'),
        ),
        migrations.AddField(
            model_name='collectionattachment',
            name='type_of_processing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='publications.ProcessingType'),
        ),
    ]
