# Generated by Django 3.0.5 on 2020-06-16 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0018_auto_20200616_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionattachment',
            name='derived_from_collection_attachment',
            field=models.ManyToManyField(blank=True, null=True, to='publications.CollectionAttachment'),
        ),
    ]
