# Generated by Django 3.0.5 on 2020-06-17 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0019_collectionattachment_derived_from_collection_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='archive',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='publications.Archive'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='authors',
            field=models.CharField(blank=True, help_text='List of authors separated by commas or <i>and</i>.', max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='callNumber',
            field=models.CharField(blank=True, default='', max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='publications.Place'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='rights',
            field=models.CharField(blank=True, default='', max_length=3000, null=True),
        ),
    ]
